AutomatedTellerMachine/AutomatedTellerMachine/Controllers/CheckingAccountController.cs
using AutomatedTellerMachine.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AutomatedTellerMachine.Controllers
{
    [Authorize]
    public class CheckingAccountController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: CheckingAccount
        public ActionResult Index()
        {
            return View();
        }

        // GET: CheckingAccount/Details
        public ActionResult Details()
        {
            var userId = User.Identity.GetUserId();
            var chekingAccount = db.CheckingAccounts.Where(c => c.ApplicationUserId == userId).First();
            return View(chekingAccount);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult DetailsForAdmin(int id)
        {
            var chekingAccount = db.CheckingAccounts.Find(id);
            return View("Details", chekingAccount);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult List()
        {
            return View(db.CheckingAccounts.ToList());
        }

        // GET: CheckingAccount/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CheckingAccount/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CheckingAccount/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: CheckingAccount/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CheckingAccount/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CheckingAccount/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

AutomatedTellerMachine/AutomatedTellerMachine/Controllers/HomeController.cs
using AutomatedTellerMachine.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AutomatedTellerMachine.Controllers
{
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [Authorize]
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            var checkingAccountId = db.CheckingAccounts.Where(c => c.ApplicationUserId == userId).First().Id;
            ViewBag.CheckingAccountId = checkingAccountId;
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.CustomerMessage = "Having problems.Tell us here!";

            return View();
        }

        [HttpPost]
        public ActionResult Contact(string message)
        {
            //TO DO : send message
            ViewBag.CustomerMessage = "We got your message.Thank you";

            return PartialView("_ContactThanks");
        }

        public ActionResult Serial(string letterCase)
        {
            var serial = "TEST";
            if (letterCase == "lower")
            {
                return Content(serial.ToLower());
            }

            return Content(serial);
            //return Json(new { name = "serial", value = serial }, JsonRequestBehavior.AllowGet);
            //return RedirectToAction("About");
        }
    }
}

AutomatedTellerMachine/AutomatedTellerMachine/Controllers/TransactionController.cs
using AutomatedTellerMachine.Models;
using AutomatedTellerMachine.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AutomatedTellerMachine.Controllers
{
    [Authorize]
    public class TransactionController : Controller
    {
        private IApplicationDbContext db;

        public TransactionController()
        {
            db = new ApplicationDbContext();
        }

        public TransactionController(IApplicationDbContext dbContext)
        {
            db = dbContext;
        }

        // GET: Transaction/Deposit
        public ActionResult Deposit(int checkingAccountId)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Deposit(Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                db.Transactions.Add(transaction);
                db.SaveChanges();
                var service = new CheckingAccountService(db);
                service.UpdateBalance(transaction.CheckingAccountId);
                return RedirectToAction("Index", "Home");
            }

            return View();
        }
    }
}

AutomatedTellerMachine/AutomatedTellerMachine/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AutomatedTellerMachine/AutomatedTellerMachine/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

<div id="formSection">
    <h3>@ViewBag.CustomerMessage</h3>
    <form method="post" id="contactForm">
        <textarea name="message" id="message"></textarea>
        <input type="submit" value="Send" />
    </form>
    <img src="~/Content/Images/Clock.png" id="progress" style="display:none;" />
</div>

@section scripts{
    <script>
        $('#contactForm').submit(function () {
            $('#progress').show();
            $.post('', { message: $('#message').val() })
            .done(function (response) {
                setTimeout(function () { $('#formSection').html(response); }, 2000);
            });
            return false;
        });
    </script>
}


@*
    Partial page using jquery.unobtrusive-ajax.js
    <div id="formSection">
        <h3>@ViewBag.CustomerMessage</h3>
        @using (Ajax.BeginForm(
            new AjaxOptions
            {
                HttpMethod = "post",
                InsertionMode = InsertionMode.Replace,
                UpdateTargetId = "formSection"
            }))
        {
        <textarea name="message"></textarea>
        <input type="submit" value="Send" />
        }
    </div>

    @section scripts{
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    }

*@

AutomatedTellerMachine/AutomatedTellerMachine/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    <div class="col-md-6 margin-top-10">
        <a href="#" class="btn btn-info btn-block">
            <span class="glyphicon glyphicon-arrow-down"></span> Withdrawal
        </a>
        <a href="#" class="btn btn-info btn-block">
            <span class="glyphicon glyphicon-flash"></span> Quick cash 100
        </a>
        <a href="@Url.Action("Details", "CheckingAccount")" class="btn btn-info btn-block">
            <span class="glyphicon glyphicon-question-sign"></span> Balance Inquery
        </a>
    </div>
    <div class="col-md-6 margin-top-10">
        <a href="#" class="btn btn-info btn-block">
            <span class="glyphicon glyphicon-print"></span> Print Statement
        </a>
        <a href="#" class="btn btn-info btn-block">
            <span class="glyphicon glyphicon-transfer"></span> Transfer Funds
        </a>
        <a href="@Url.Action("Deposit", "Transaction", new { checkingAccountId = ViewBag.CheckingAccountId})" class="btn btn-info btn-block">
            <span class="glyphicon glyphicon-arrow-up"></span> Deposit
        </a>
    </div>
</div>

AutomatedTellerMachine/AutomatedTellerMachine/Views/Home/_ContactThanks.cshtml
<h3>@ViewBag.CustomerMessage</h3>